# Generated by Django 3.2.5 on 2021-11-15 11:56
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("short_title", models.CharField(max_length=70)),
                ("long_title", models.CharField(max_length=256)),
                ("actual_price", models.PositiveIntegerField()),
                ("selling_price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("shipping_fee", models.PositiveIntegerField(default=0)),
                ("description", models.TextField()),
                ("discount", models.PositiveIntegerField()),
                ("tagline", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Mobiles", "Mobiles"),
                            ("Smart Wearable Tech", "Smart Wearable Tech"),
                            ("Speakers", "Speakers"),
                            ("Laptops", "Laptops"),
                            ("Television", "Television"),
                            ("Gaming Laptop", "Gaming Laptop"),
                            ("Tablets", "Tablets"),
                        ],
                        max_length=70,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MI", "MI"),
                            ("RealMe", "RealMe"),
                            ("Samsung", "Samsung"),
                            ("Apple", "Apple"),
                            ("OnePlus", "OnePlus"),
                            ("Boat", "Boat"),
                            ("Boult", "Boult"),
                            ("JBL", "JBL"),
                            ("Dell", "Dell"),
                            ("HP", "HP"),
                            ("Asus", "Asus"),
                            ("Acer", "Acer"),
                            ("Lenovo", "Lenovo"),
                            ("Thomson", "Thomson"),
                            ("VU", "VU"),
                            ("Sony", "Sony"),
                        ],
                        max_length=70,
                        null=True,
                    ),
                ),
                ("max_product_quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        related_query_name="product",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product", models.ManyToManyField(to="products.Product")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        related_query_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wishlist",
            },
        ),
        migrations.CreateModel(
            name="SpecificationTitle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=90)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification_titles",
                        related_query_name="specification_title",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Specifications",
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                ("value", models.CharField(max_length=256)),
                (
                    "specification_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        related_query_name="specification",
                        to="products.specificationtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RatingAndReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("likes", models.PositiveIntegerField()),
                ("dislikes", models.PositiveIntegerField()),
                ("stars", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("title", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_and_reviews",
                        related_query_name="rating_and_review",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_and_reviews",
                        related_query_name="rating_and_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_url", models.ImageField(upload_to="product_images/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        related_query_name="image",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
