# Generated by Django 3.2.5 on 2022-03-03 11:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20220303_1636"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratingandreview",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratingandreview",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
