# Generated by Django 3.2.5 on 2022-03-07 06:16
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0007_auto_20220303_1721"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserRatingsAndReviewsLikes",
            new_name="RatingsAndReviewsLike",
        ),
        migrations.RemoveField(
            model_name="ratingandreview",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="ratingandreview",
            name="likes",
        ),
        migrations.AlterField(
            model_name="ratingandreview",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="ratingandreview",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
