# Generated by Django 3.2.5 on 2021-11-20 06:40
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveForLater",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("products", models.ManyToManyField(to="products.Product")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="save_for_later",
                        related_query_name="save_for_later",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
