export const SET_USER = "USER";
export const SET_COOKIE = "SET_COOKIE";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const INIT_STATE = "INIT_STATE";
